### ISSUE TITLE
Update to uhub 3.0.0

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/repofs#30]

**Comment by mklabs** [comment]
Unfortunately, I get an error while running the tests with both 3.0.0 and 3.1.0 version of uhub.

```
API tests LocalUtils .status should return list of changed files:
     Error: Error 404: 404 page not found
```

**Comment by mklabs** [comment]
cc @AaronO

**Comment by mklabs** [comment]
My bad, the breaking change for 3.0.0 is exactly that. `/status` becomes `/local/status`
